// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw9mDn3JPnyNWKZ3au0U2hC30qhnDsjaI',
    appId: '1:13247595433:web:48ce3c041cd7e9d6b3bab8',
    messagingSenderId: '13247595433',
    projectId: 'flutterfinalproje',
    authDomain: 'flutterfinalproje.firebaseapp.com',
    storageBucket: 'flutterfinalproje.firebasestorage.app',
    measurementId: 'G-N5YEP2GKJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvWiw_zXzdS4opgrY5vYrZdPSLzwE8ZCo',
    appId: '1:13247595433:android:985f0261ef2ec9e1b3bab8',
    messagingSenderId: '13247595433',
    projectId: 'flutterfinalproje',
    storageBucket: 'flutterfinalproje.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF6j6vAf0JzQyUTCbb8vuDkdjUdWSMtyE',
    appId: '1:13247595433:ios:c7cc59c6e2da07eab3bab8',
    messagingSenderId: '13247595433',
    projectId: 'flutterfinalproje',
    storageBucket: 'flutterfinalproje.firebasestorage.app',
    iosBundleId: 'com.example.dijitalKutuphane',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF6j6vAf0JzQyUTCbb8vuDkdjUdWSMtyE',
    appId: '1:13247595433:ios:c7cc59c6e2da07eab3bab8',
    messagingSenderId: '13247595433',
    projectId: 'flutterfinalproje',
    storageBucket: 'flutterfinalproje.firebasestorage.app',
    iosBundleId: 'com.example.dijitalKutuphane',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw9mDn3JPnyNWKZ3au0U2hC30qhnDsjaI',
    appId: '1:13247595433:web:a38d295522300ae5b3bab8',
    messagingSenderId: '13247595433',
    projectId: 'flutterfinalproje',
    authDomain: 'flutterfinalproje.firebaseapp.com',
    storageBucket: 'flutterfinalproje.firebasestorage.app',
    measurementId: 'G-X092DBWYQ6',
  );
}
